class DatLists {
 static const  List<Map<String, dynamic>> quranSurahs = [
  {"number": 1, "arabicName": "الفاتحة", "englishName": "Al-Fatiha", "verses": 7},
{"number": 2, "arabicName": "البقرة", "englishName": "Al-Baqara", "verses": 286},
{"number": 3, "arabicName": "آل عمران", "englishName": "Aal-E-Imran", "verses": 200},
{"number": 4, "arabicName": "النساء", "englishName": "An-Nisa", "verses": 176},
{"number": 5, "arabicName": "المائدة", "englishName": "Al-Ma'idah", "verses": 120},
{"number": 6, "arabicName": "الأنعام", "englishName": "Al-An'am", "verses": 165},
{"number": 7, "arabicName": "الأعراف", "englishName": "Al-A'raf", "verses": 206},
{"number": 8, "arabicName": "الأنفال", "englishName": "Al-Anfal", "verses": 75},
{"number": 9, "arabicName": "التوبة", "englishName": "At-Tawbah", "verses": 129},
{"number": 10, "arabicName": "يونس", "englishName": "Yunus", "verses": 109},
{"number": 11, "arabicName": "هود", "englishName": "Hud", "verses": 123},
{"number": 12, "arabicName": "يوسف", "englishName": "Yusuf", "verses": 111},
{"number": 13, "arabicName": "الرعد", "englishName": "Ar-Ra'd", "verses": 43},
{"number": 14, "arabicName": "إبراهيم", "englishName": "Ibrahim", "verses": 52},
{"number": 15, "arabicName": "الحجر", "englishName": "Al-Hijr", "verses": 99},
{"number": 16, "arabicName": "النحل", "englishName": "An-Nahl", "verses": 128},
{"number": 17, "arabicName": "الإسراء", "englishName": "Al-Isra", "verses": 111},
{"number": 18, "arabicName": "الكهف", "englishName": "Al-Kahf", "verses": 110},
{"number": 19, "arabicName": "مريم", "englishName": "Maryam", "verses": 98},
{"number": 20, "arabicName": "طه", "englishName": "Taha", "verses": 135},
{"number": 21, "arabicName": "الأنبياء", "englishName": "Al-Anbiya", "verses": 112},
{"number": 22, "arabicName": "الحج", "englishName": "Al-Hajj", "verses": 78},
{"number": 23, "arabicName": "المؤمنون", "englishName": "Al-Mu'minun", "verses": 118},
{"number": 24, "arabicName": "النور", "englishName": "An-Nur", "verses": 64},
{"number": 25, "arabicName": "الفرقان", "englishName": "Al-Furqan", "verses": 77},
{"number": 26, "arabicName": "الشعراء", "englishName": "Ash-Shu'ara", "verses": 227},
{"number": 27, "arabicName": "النمل", "englishName": "An-Naml", "verses": 93},
{"number": 28, "arabicName": "القصص", "englishName": "Al-Qasas", "verses": 88},
{"number": 29, "arabicName": "العنكبوت", "englishName": "Al-Ankabut", "verses": 69},
{"number": 30, "arabicName": "الروم", "englishName": "Ar-Rum", "verses": 60},
{"number": 31, "arabicName": "لقمان", "englishName": "Luqman", "verses": 34},
{"number": 32, "arabicName": "السجدة", "englishName": "As-Sajda", "verses": 30},
{"number": 33, "arabicName": "الأحزاب", "englishName": "Al-Ahzab", "verses": 73},
{"number": 34, "arabicName": "سبأ", "englishName": "Saba", "verses": 54},
{"number": 35, "arabicName": "فاطر", "englishName": "Fatir", "verses": 45},
{"number": 36, "arabicName": "يس", "englishName": "Ya-Sin", "verses": 83},
{"number": 37, "arabicName": "الصافات", "englishName": "As-Saffat", "verses": 182},
{"number": 38, "arabicName": "ص", "englishName": "Sad", "verses": 88},
{"number": 39, "arabicName": "الزمر", "englishName": "Az-Zumar", "verses": 75}]
;


}